REPORT z_day22_alv_practice.

" Step 1: Define structure
TYPES: BEGIN OF ty_emp,
         empid   TYPE i,
         empname TYPE string,
         salary  TYPE i,
       END OF ty_emp.

" Step 2: Internal table
DATA: it_data TYPE TABLE OF ty_emp,
      wa_data TYPE ty_emp.

" Sample Data
wa_data-empid = 1.
wa_data-empname = 'Rohit'.
wa_data-salary = 50000.
APPEND wa_data TO it_data.

wa_data-empid = 2.
wa_data-empname = 'Amit'.
wa_data-salary = 65000.
APPEND wa_data TO it_data.

wa_data-empid = 3.
wa_data-empname = 'Neha'.
wa_data-salary = 72000.
APPEND wa_data TO it_data.

" Step 3: Field Catalog
DATA: gt_fcat TYPE slis_t_fieldcat_alv,
      gs_fcat TYPE slis_fieldcat_alv.

" Important fields:
" TYP → Header type
" ‘H’ = Header
" ‘S’ = Selection text
" ‘A’ = Action text
" INFO → Header text

DATA: gt_header TYPE slis_t_listheader,
      gs_header TYPE slis_listheader.

CLEAR gs_header.
gs_header-typ  = 'H'.
gs_header-info = 'Employee Salary Report'.
APPEND gs_header TO gt_header.

CLEAR gs_header.
gs_header-typ  = 'S'.
gs_header-info = 'Generated By: Rohit'.
APPEND gs_header TO gt_header.

CLEAR gs_header.
gs_header-typ  = 'S'.
gs_header-info = |Date: { sy-datum }|.
APPEND gs_header TO gt_header.


" Column 1: Employee ID
CLEAR gs_fcat.
gs_fcat-fieldname = 'EMPID'.
gs_fcat-coltext   = 'Employee ID'.
gs_fcat-outputlen = 10.
APPEND gs_fcat TO gt_fcat.

" Column 2: Employee Name
CLEAR gs_fcat.
gs_fcat-fieldname = 'EMPNAME'.
gs_fcat-coltext   = 'Name'.
gs_fcat-outputlen = 20.
APPEND gs_fcat TO gt_fcat.

" Column 3: Salary (with SUM)
CLEAR gs_fcat.
gs_fcat-fieldname = 'SALARY'.
gs_fcat-coltext   = 'Salary'.
gs_fcat-outputlen = 10.
gs_fcat-do_sum    = 'X'. " total salary at bottom
APPEND gs_fcat TO gt_fcat.

" Step 4: ALV Call
CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
  EXPORTING
    i_callback_program = sy-repid
    it_list_header     = gt_header
  TABLES
    t_outtab           = it_data
    t_fieldcat         = gt_fcat.
